image: python:3.10.13

variables:
  PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - lint
  - test

cache:
  paths:
    - .cache/pip
    - venv/
    - $PRE_COMMIT_HOME

before_script:
  - apt-get update && apt-get install ffmpeg libsm6 libxext6 -y # opencv dependency
  - python --version ; pip --version # For debugging

lint:
  script:
    - pip install pre-commit flake8 black isort
    - pre-commit run --all-files

test:
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-cpu.txt
    - pip install pytest
    - ls -a
    - pwd
    - pip install .
    - pytest --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml
